### ISSUE TITLE
Electric Power Compatibility with Qptech

### ISSUE THREAD

**Issue by EngineOfDarkness** [anluin/Electricity#7]
Would be cool if there could be some rudimentary interoperability between Qptech and this mod with regards to the electricity system

https://github.com/wqpvs/qptech

**Comment by anluin** [comment]
Compatibility with other mods is not and will not be on my to-do list for the time being. 

I might think about this once there is a certain degree of stability (I'm sure how I really want to implement the underlying systems).

**Comment by UrbanSide** [comment]
> Compatibility with other mods is not and will not be on my to-do list for the time being.
> 
> I might think about this once there is a certain degree of stability (I'm sure how I really want to implement the underlying systems).

It's a pity, I would like to see at least an addon for energy compatibility, because everything is cool in your mod, but there are not enough wires like in QPTech
